(dp1
S'output'
p2
S"<type 'exceptions.IndexError'> list index out of range"
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f04fd985530, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 8>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 95, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 16, in index\n    aluno_id= db(db.cadastro.id>0).select(\'cadastro.nome_crianca\')== request.args[0]\nIndexError: list index out of range\n'
p11
s.